### ISSUE TITLE
problems.csv eilutė su ID 3357

### ISSUE THREAD

**Issue by kasparas-adomaitis** [vilnius/problemos#1]
berods ten yra kažkoks kabliataškis ar panašiai ir nėra kaip gražiai nuskaityti (na, nebent ištrini ta eilute..)

**Comment by povilasp** [comment]
kolega, gal galima konkrečiau? kur yra?

**Comment by povilasp** [comment]
a nemačiau subjecto

**Comment by kasparas-adomaitis** [comment]
ok, sorry, gal ir nekorektiškai užpildžiau.. :)
