### ISSUE TITLE
Problemos importuojant duomenis CSV formatu.

### ISSUE THREAD

**Issue by VytautasGipiskis** [vilnius/problemos#3]
Nei viena aplikacija, skaitanti CSV formatą neatvaizduoja failo problemos.csv korektiškai.

Pagrindinės klaidos:
9 eil. (ID 31) – problemos aprašymo tekstas turi naujos eilutės simbolių (\n) simbolių. Viena eilutė suprantama, kaip kelios eilutės
9 eil. (ID 31) – tekste dvigubos kabutės, pvz. [...draužiamieji kelio ženklai ""Sustoti draudžiama"", kurių ten niekada nebuvo...]
38 eil. (ID 57) – pranešimo tekste kabliataškiai suprantami, kaip naujos laukų reikšmės
66 eil (ID 75) – tekste kabliataškiai [...Įspėti atliekas tvarkanti įmonė &amp;quot;VSA Vilnius&amp;quot; ir gyvenamųjų namų administratorius UA...]

**Comment by atvirasvilnius** [comment]
Suformuotas naujas failas https://github.com/vilnius/problemos/blob/master/data/tvarkau_miesta_problems_list.csv
